apiVersion: traefik.io/v1alpha1
kind: TraefikService
metadata:
  name: api-weighted
spec:
  weighted:
    services:
      - name: api-v1
        port: 80
        weight: 70
      - name: api-v2
        port: 80
        weight: 30



use as reference:

services:
  - name: api-weighted
    kind: TraefikService

