apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo-app.fullname" . }}-task-service
  namespace: {{ include "todo-app.namespace" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: task-service
spec:
  replicas: {{ .Values.taskService.replicaCount }}
  selector:
    matchLabels:
      {{- include "todo-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: task-service
  template:
    metadata:
      labels:
        {{- include "todo-app.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: task-service
    spec:
      initContainers:
      - name: wait-deps
        image: busybox:1.36
        command: 
        - sh
        - -c
        - |
          until nc -zv {{ include "todo-app.fullname" . }}-postgres.{{ .Release.Namespace }}.svc.cluster.local 5432; do echo "waiting for postgres"; sleep 2; done
          until nc -zv {{ include "todo-app.fullname" . }}-user-service.{{ .Release.Namespace }}.svc.cluster.local 8000; do echo "waiting for user-service"; sleep 2; done
          until nc -zv {{ include "todo-app.fullname" . }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local 5672; do echo "waiting for rabbitmq"; sleep 2; done
      containers:
      - name: task-service
        image: "{{ .Values.taskService.image.repository }}:{{ .Values.taskService.image.tag }}"
        imagePullPolicy: {{ .Values.taskService.image.pullPolicy }}
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: DATABASE_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@{{ include "todo-app.fullname" . }}-postgres.{{ .Release.Namespace }}.svc.cluster.local:5432/$(POSTGRES_DB)?sslmode=disable
        - name: PORT
          value: "8001"
        - name: USER_SERVICE_URL
          value: http://{{ include "todo-app.fullname" . }}-user-service.{{ .Release.Namespace }}.svc.cluster.local:8000
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: rabbitmq-secret
              key: RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_URL
          value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@{{ include "todo-app.fullname" . }}-rabbitmq.{{ .Release.Namespace }}.svc.cluster.local:5672/
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          {{- toYaml .Values.taskService.resources | nindent 10 }}