apiVersion: v2
name: todo-app
description: A Helm chart for Todo application with PostgreSQL, RabbitMQ, and microservices
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "16.7.27"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: rabbitmq
    version: "16.0.14"
    repository: "https://charts.bitnami.com/bitnami"
    condition: rabbitmq.enabled

