apiVersion: v1
kind: Pod
metadata:
  name: configmap-posix-demo
spec:
  containers:
    - name: configmap-posix
      image: busybox
      command: ["sh", "-c", "env && sleep 3600"]

      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: player-posix-demo






