apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: todo-ns
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: mgmt
    port: 15672
    targetPort: 15672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mgmt
  namespace: todo-ns
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - name: mgmt
    port: 15672
    targetPort: 15672
    nodePort: 31672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
        envFrom:
        - secretRef:
            name: rabbitmq-secret
        readinessProbe:
          exec:
            command: ["sh","-c","rabbitmq-diagnostics -q ping"]
          initialDelaySeconds: 20
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5672
          initialDelaySeconds: 30
          periodSeconds: 10
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
      volumes:
      - name: rabbitmq-data
        persistentVolumeClaim:
          claimName: rabbitmq-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
  namespace: todo-ns
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: nfs-client
  resources:
    requests:
      storage: 2Gi