apiVersion: v1
kind: Service
metadata:
  name: task-service
  namespace: todo-ns
spec:
  type: NodePort
  selector:
    app: task-service
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-service
  namespace: todo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: task-service
  template:
    metadata:
      labels:
        app: task-service
    spec:
      initContainers:
      - name: wait-deps
        image: busybox:1.36
        command: ["sh","-c","until nc -zv postgres.todo-ns.svc.cluster.local 5432; do echo waiting for postgres; sleep 2; done; until nc -zv user-service.todo-ns.svc.cluster.local 8000; do echo waiting for user-service; sleep 2; done; until nc -zv rabbitmq.todo-ns.svc.cluster.local 5672; do echo waiting for rabbitmq; sleep 2; done"]
      containers:
      - name: task-service
        image: zahid03/todo-task-service:latest
        ports:
        - containerPort: 8001
        env:
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef: {name: db-secret, key: POSTGRES_DB}
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef: {name: db-secret, key: POSTGRES_USER}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef: {name: db-secret, key: POSTGRES_PASSWORD}
        - name: DATABASE_URL
          value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres.todo-ns.svc.cluster.local:5432/$(POSTGRES_DB)?sslmode=disable
        - name: PORT
          value: "8001"
        - name: USER_SERVICE_URL
          value: http://user-service.todo-ns.svc.cluster.local:8000
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef: {name: rabbitmq-secret, key: RABBITMQ_DEFAULT_USER}
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef: {name: rabbitmq-secret, key: RABBITMQ_DEFAULT_PASS}
        - name: RABBITMQ_URL
          value: amqp://$(RABBITMQ_USER):$(RABBITMQ_PASS)@rabbitmq.todo-ns.svc.cluster.local:5672/
        readinessProbe:
          tcpSocket:
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 10