apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-postgres
  namespace: {{ include "todo-app.namespace" . }}
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  ports:
  - port: {{ .Values.postgresql.service.port }}
    targetPort: 5432
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres