apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  volumes:
  - name: hostpath-vol
    hostPath:
      path: /home/zahid
      type: DirectoryOrCreate  # Ensures directory exists
  containers:
  - name: hostpath-pod
    image: busybox
    command: 
      - /bin/sh
      - -c
      - |
        echo Hello Team, This is Sample File for HostVolume - $(date) >> /output/output.txt;
        echo "File written. Container will keep running...";
        tail -f /dev/null
    volumeMounts:
    - name: hostpath-vol
      mountPath: /output
