apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /home/zahid/Technonext/WorkSpace1/Kubernetes/Kubernetes/Kubernetes/K8s-Storage
    server: 10.70.34.68

