apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: todo-ingress
type: Opaque
stringData:
  POSTGRES_DB: todo_db
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
  namespace: todo-ingress
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: admin123